### ISSUE TITLE
[BUG] Can't install with npm

### ISSUE THREAD

**Issue by Nes-si** [highfidelity/hifi-spatial-audio-js#133]
When I run `npm install hifi-spatial-audio`, I get the error:
```
npm ERR! code 1
npm ERR! path /Users/nss/Code/tutors/hi-fi-spatial-audio/hifi-simple-server/node_modules/wrtc
npm ERR! command failed
npm ERR! command sh -c node scripts/download-prebuilt.js
npm ERR! /bin/sh: node-pre-gyp: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nss/.npm/_logs/2021-06-11T17_29_04_034Z-debug.log
```
I use npm v7.16.0, Node v16.2.0.

If I use Yarn (v1.22.10) for installation, it works correct.

**Comment by zfox23** [comment]
Hi @Nes-si! It looks like you don't have `node-pre-gyp` installed or accessible to NodeJS via `npm`.

You can try installing `node-pre-gyp` with: `npm install -g node-pre-gyp`. After that, you can try `npm install hifi-spatial-audio` again.

Are you able to get `hifi-spatial-audio` working properly via a Yarn installation?

**Comment by Nes-si** [comment]
Maybe I don't understand something, but shouldn't you add `node-pre-gyp` in dependencies? For me, it's not obvious to install it.

**Comment by zfox23** [comment]
You're right - that is one potential solution.

However, because this problem is actually with building `wrtc` - and not `hifi-spatial-audio-js` itself - adding `node-pre-gyp` as a dependency for `hifi-spatial-audio-js` isn't quite accurate and shouldn't be necessary. In fact, `node-pre-gyp` is already included as a dependency of `wrtc`, but, for whatever reason, NodeJS on your particular system didn't pick up that dependency during installation.

There are so many reasons that this might happen, but we don't want to get into the business of fixing Node's problems, or `wrtc`'s problems. In this hopefully-rare case, we can troubleshoot your issue individually, and get you developing with our client library.

If we find that other folks are having this problem as well, we will talk internally about solutions, such as adding `node-pre-gyp` as a dependency to our project.
